<?php

function minelogin_form_user_register_form_alter(&$form, &$form_state, $form_id){
  $form['#submit'][] = 'minelogin_form_register_submit';
  return $form;
}

function minelogin_form_register_submit($form, &$form_state){
 $form_state['redirect'] = 'user/check-mail';
}

function minelogin_form_user_profile_form_alter(&$form, &$form_state, $form_id){
  global $user; 
  if($form['#user']->uid == $user->uid){
	  $form['minepass'] = array(
	      '#type' => 'textfield',
	      '#title' => 'Minecraft password',    
	      '#maxlength' => 15,
	      '#size' => 15,      
	  ); 
	  $form['#validate'][] = 'minelogin_form_validate';
	  $form['actions']['submit']['#submit'][] = 'minelogin_form_profile_submit';
	  return $form;
  }
}

function minelogin_form_profile_submit($form, &$form_state) {
  global $user;
  $pass = $form_state['values']['minepass'];
  $pass = hash('SHA512', $pass);
  db_merge('minelogin')
      ->key(array('id' => $user->uid))
      ->fields(array(
            'id' => $user->uid,
            'minepass' => $pass,
            'username'=>$user->name,
            'mail'=>$user->mail,
      ))
      ->execute();
  
  
  $form_state['redirect'] = 'user';
  drupal_set_message("Successfully saved Minecraft password");
}

function minelogin_form_validate($form, &$form_state) {
  if (!($form_state['values']['minepass'] < 6)){
    form_set_error('minepass', t('La password deve essere di 6 o più caratteri.'));
  }
}

function minelogin_user_delete($account) {
  db_delete('minelogin')->condition('id', $account->uid)->execute();
}

function minelogin_menu(){
  $items['user/check-mail'] = array(
    'title' => 'Check your mail',
    'description' => 'check email page.',
    'page callback' => 'minelogin_page',
    'access arguments' => array('access content'),
  );
  return $items;
}

function minelogin_page(){
  return theme('minelogin_template');
}
   

function minelogin_theme(){
  return array(
    'minelogin_template' => array(
      'template' => 'check-email',
    ),
  );
}